export const ARKHAM_CARDS_GRAPHQL_URL = process.env.ARKHAM_CARDS_GRAPHQL_URL;
export const ARKHAM_DIVIDER_CORE_URL = process.env.ARKHAM_DIVIDER_CORE_URL;
export const ARKHAM_CARDS_REPO_RAW_URL = process.env.ARKHAM_CARDS_REPO_RAW_URL;
export const ARKHAM_CARDS_DATA_REPO_RAW_URL =
	process.env.ARKHAM_CARDS_DATA_REPO_RAW_URL;

export const ARKHAM_BUILD_FAN_REPO_ARCHIVE_URL =
	process.env.ARKHAM_BUILD_FAN_REPO_ARCHIVE_URL;
export const ARKHAM_BUILD_FAN_REPO_FOLDER_NAME =
	process.env.ARKHAM_BUILD_FAN_REPO_FOLDER_NAME;
