export const GOOGLE_DRIVE_FOLDER_ID = process.env.GOOGLE_DRIVE_FOLDER_ID;

export const GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL =
	process.env.GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL;
export const GOOGLE_SERVICE_ACCOUNT_CLIENT_ID =
	process.env.GOOGLE_SERVICE_ACCOUNT_CLIENT_ID;
export const GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY =
	process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY;
